
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::618480995829:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-XTjnIl6wKY9A
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::618480995829:user/suresh
      username: suresh  
kind: ConfigMap
metadata:
  creationTimestamp: "2025-10-19T04:59:53Z"
  name: aws-auth
  namespace: kube-system
  uid: 9e29c12e-fda7-480e-86cd-761890c685a0